name: mon workflow de test


on:
  push: 


jobs:
  mon-test:
    runs-on: ubuntu-latest
    steps:
      - name: Installer cowsay
        uses: mscoutermarsh/cowsays-action@v1
        with:
          text: "Careful pardner! Issue ${{ github.event.issue.number }} has been opened !"
